apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: stackrox-central-services
  namespace: stackrox
spec:
  central:
    declarativeConfiguration:
      configMaps:
      - name: "declarative-configurations"
    exposure:
      route:
        enabled: true
  scannerV4:
    scannerComponent: Enabled
